### ISSUE TITLE
fsync to sync writes to disk

### ISSUE THREAD

**Issue by dahmanator** [ColinIanKing/sluice#1]
Thanks for sharing such a great tool. I am using sluice to generate IO with various throughputs to test disk replication.

I put in a couple fsync system calls to make sure the write were flushing to disk and have been able to get sustained writes at the rate of my choosing. This is very helpful. 

$ git diff sluice.c
diff --git a/sluice.c b/sluice.c
index 533b93a..d244d38 100644
--- a/sluice.c
+++ b/sluice.c
@@ -1318,6 +1318,7 @@ int main(int argc, char **argv)
                                ret = EXIT_WRITE_ERROR;
                                goto tidy;
                        }
+                       fsync(fdout);
                }

                /* -t Tee mode output */
@@ -1336,6 +1337,7 @@ redo_write:
                                        goto tidy;
                                }
                        }
+                       fsync(fdtee);
                }
                if (eof)
                        break;

**Comment by ColinIanKing** [comment]
Thanks for this contribution. I think sync'ing on fdtee may be redundant. I'll look at this and see if I can optimize this code a little to reduce redundant fsync's on non-file system file descriptors.

**Comment by ColinIanKing** [comment]
Fix committed, new -F option to force fsync on writes, will disable fsync if output can't be fsync'd to.

commit ef31c79b020e0843a1963dd8cccb5a321b43ecb1
Author: Colin Ian King <colin.i.king@gmail.com>
Date:   Thu Jan 18 15:53:24 2024 +0000

    Add -F option to fsync data to file
